## Experimento 6 — List Comprehensions + NumPy
**Objetivo:** criar listas com comprehensions e trabalhar com arrays/matrizes.

**Enunciado:**  
1. Gere uma lista com os **quadrados de 1 a 10** usando list comprehension.  
2. Crie um **array NumPy** a partir dessa lista e uma **matriz 3×3** usando `reshape`.  
3. **Tarefa Extra:** **filtre apenas os quadrados pares** usando compreensão de listas e, no array NumPy, use **indexação booleana**.


[![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flavioluizseixas/aprendizado-de-maquina-na-saude/blob/main/0-Nivelamento/Experimento_06.ipynb)

In [1]:
import numpy as np

In [2]:
# Código-base
quadrados = [n**2 for n in range(1, 11)]
print("Quadrados:", quadrados)

arr = np.array(quadrados)
mat = arr[:9].reshape(3, 3)
print("Array:", arr)
print("Matriz 3x3:\n", mat)


Quadrados: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Array: [  1   4   9  16  25  36  49  64  81 100]
Matriz 3x3:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Adaptação (Extra)
- Lista: `[q for q in quadrados if q % 2 == 0]`
- NumPy: `arr[arr % 2 == 0]`
